version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    working_directory: ~/repo
    environment:
      - AWS_REGION: us-east-1
      - AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run: apk add nodejs npm
      - run: npm install
      - run: npm run --silent cdk -- --verbose --app 'npm run ts-node -- ./examples/private-cloud.ts' synth > template.yml
