Resources:
  PrivateCloud8ABF1600:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Resource
  PrivateCloudPublicsubnetSubnet1Subnet0900C094:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet1
        - Key: aws-cdk:subnet-name
          Value: Public subnet
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/Subnet
  PrivateCloudPublicsubnetSubnet1RouteTableD366E6CE:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet1
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/RouteTable
  PrivateCloudPublicsubnetSubnet1RouteTableAssociation6A002635:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet1RouteTableD366E6CE
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet1Subnet0900C094
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/RouteTableAssociation
  PrivateCloudPublicsubnetSubnet1DefaultRoute4451E5DE:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet1RouteTableD366E6CE
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: PrivateCloudIGW4529FD35
    DependsOn:
      - PrivateCloudVPCGW274FC782
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/DefaultRoute
  PrivateCloudPublicsubnetSubnet1EIP1C091BA9:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/EIP
  PrivateCloudPublicsubnetSubnet1NATGateway5DE2284E:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - PrivateCloudPublicsubnetSubnet1EIP1C091BA9
          - AllocationId
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet1Subnet0900C094
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet1
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet1/NATGateway
  PrivateCloudPublicsubnetSubnet2Subnet8974C324:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet2
        - Key: aws-cdk:subnet-name
          Value: Public subnet
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/Subnet
  PrivateCloudPublicsubnetSubnet2RouteTableBCC671AB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet2
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/RouteTable
  PrivateCloudPublicsubnetSubnet2RouteTableAssociation717C6176:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet2RouteTableBCC671AB
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet2Subnet8974C324
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/RouteTableAssociation
  PrivateCloudPublicsubnetSubnet2DefaultRoute91077F9A:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet2RouteTableBCC671AB
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: PrivateCloudIGW4529FD35
    DependsOn:
      - PrivateCloudVPCGW274FC782
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/DefaultRoute
  PrivateCloudPublicsubnetSubnet2EIP343D686A:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/EIP
  PrivateCloudPublicsubnetSubnet2NATGateway0495F905:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - PrivateCloudPublicsubnetSubnet2EIP343D686A
          - AllocationId
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet2Subnet8974C324
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet2
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet2/NATGateway
  PrivateCloudPublicsubnetSubnet3Subnet4E01B582:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet3
        - Key: aws-cdk:subnet-name
          Value: Public subnet
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/Subnet
  PrivateCloudPublicsubnetSubnet3RouteTable35E21898:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet3
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/RouteTable
  PrivateCloudPublicsubnetSubnet3RouteTableAssociation1001C539:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet3RouteTable35E21898
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet3Subnet4E01B582
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/RouteTableAssociation
  PrivateCloudPublicsubnetSubnet3DefaultRouteDC547F09:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPublicsubnetSubnet3RouteTable35E21898
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: PrivateCloudIGW4529FD35
    DependsOn:
      - PrivateCloudVPCGW274FC782
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/DefaultRoute
  PrivateCloudPublicsubnetSubnet3EIP33BF3812:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/EIP
  PrivateCloudPublicsubnetSubnet3NATGatewayFA9F7E2A:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - PrivateCloudPublicsubnetSubnet3EIP33BF3812
          - AllocationId
      SubnetId:
        Ref: PrivateCloudPublicsubnetSubnet3Subnet4E01B582
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Public subnetSubnet3
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Public subnetSubnet3/NATGateway
  PrivateCloudPrivatesubnetSubnet1Subnet82CF5BB9:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet1
        - Key: aws-cdk:subnet-name
          Value: Private subnet
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet1/Subnet
  PrivateCloudPrivatesubnetSubnet1RouteTableF5D1E7C0:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet1
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet1/RouteTable
  PrivateCloudPrivatesubnetSubnet1RouteTableAssociationA24DF8DE:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet1RouteTableF5D1E7C0
      SubnetId:
        Ref: PrivateCloudPrivatesubnetSubnet1Subnet82CF5BB9
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private
        subnetSubnet1/RouteTableAssociation
  PrivateCloudPrivatesubnetSubnet1DefaultRouteFAF252E8:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet1RouteTableF5D1E7C0
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: PrivateCloudPublicsubnetSubnet1NATGateway5DE2284E
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet1/DefaultRoute
  PrivateCloudPrivatesubnetSubnet2Subnet15AB999A:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.4.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet2
        - Key: aws-cdk:subnet-name
          Value: Private subnet
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet2/Subnet
  PrivateCloudPrivatesubnetSubnet2RouteTable7B99E304:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet2
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet2/RouteTable
  PrivateCloudPrivatesubnetSubnet2RouteTableAssociation8E1EE0FB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet2RouteTable7B99E304
      SubnetId:
        Ref: PrivateCloudPrivatesubnetSubnet2Subnet15AB999A
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private
        subnetSubnet2/RouteTableAssociation
  PrivateCloudPrivatesubnetSubnet2DefaultRoute86933B7F:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet2RouteTable7B99E304
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: PrivateCloudPublicsubnetSubnet2NATGateway0495F905
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet2/DefaultRoute
  PrivateCloudPrivatesubnetSubnet3Subnet79E93465:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.5.0/24
      VpcId:
        Ref: PrivateCloud8ABF1600
      AvailabilityZone: us-east-1c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet3
        - Key: aws-cdk:subnet-name
          Value: Private subnet
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet3/Subnet
  PrivateCloudPrivatesubnetSubnet3RouteTable02040919:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud/Private subnetSubnet3
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet3/RouteTable
  PrivateCloudPrivatesubnetSubnet3RouteTableAssociation656E3F69:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet3RouteTable02040919
      SubnetId:
        Ref: PrivateCloudPrivatesubnetSubnet3Subnet79E93465
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private
        subnetSubnet3/RouteTableAssociation
  PrivateCloudPrivatesubnetSubnet3DefaultRoute15093A6E:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateCloudPrivatesubnetSubnet3RouteTable02040919
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: PrivateCloudPublicsubnetSubnet3NATGatewayFA9F7E2A
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/Private subnetSubnet3/DefaultRoute
  PrivateCloudIGW4529FD35:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PrivateCloudStack/PrivateCloud
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/IGW
  PrivateCloudVPCGW274FC782:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: PrivateCloud8ABF1600
      InternetGatewayId:
        Ref: PrivateCloudIGW4529FD35
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloud/VPCGW
  PrivateCloudSecurityGroupC031206E:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PrivateCloudStack/PrivateCloudSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress: []
      VpcId:
        Ref: PrivateCloud8ABF1600
    Metadata:
      aws:cdk:path: PrivateCloudStack/PrivateCloudSecurityGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.28.0,@aws-cdk/aws-cloudwatch=0.28.0,@aws-cdk/aws-ec2=0.28.0,@aws-cdk/aws-iam=0.28.0,@aws-cdk/cdk=0.28.0,@aws-cdk/cx-api=0.28.0,@aws-cdk/region-info=0.28.0,jsii-runtime=node.js/v8.11.2

